In [1]:
# --- Setup and Configuration ---
import nest_asyncio
import os
import re
import ast

# Apply nest_asyncio for running asyncio in environments like Jupyter/IPython
nest_asyncio.apply()

# --- Data Handling and Vectorization ---
import numpy as np
import pandas as pd
from tqdm import tqdm
from datasets import Dataset, load_dataset, load_from_disk
from sklearn.preprocessing import LabelEncoder
from sentence_transformers import SentenceTransformer

# --- Vector Database Client (Qdrant) ---
from qdrant_client import QdrantClient
from qdrant_client.models import (
    VectorParams,
    Distance,
    Filter,
    FieldCondition,
    MatchValue
)

# --- Model Imports ---
# Assuming BankingClassifier is a custom class defined in this module path
from artifacts.intent_classifier import BankingClassifier

# --- LLM and Ragas Evaluation Imports ---
# For LangChain/OpenAI integration with Ragas
from langchain_openai import ChatOpenAI
from openai import OpenAI
from ragas.llms import LangchainLLMWrapper
from ragas.run_config import RunConfig
from ragas import evaluate
from ragas.metrics import (
    context_recall,
    context_precision,
    answer_correctness,
    answer_similarity
)


from fastembed import SparseTextEmbedding

# Initialize your sparse encoder (do this once outside the function)
# sparse_encoder = SparseTextEmbedding(model_name="prithivida/Splade_PP_en_v1")

# --- Utility/Serialization ---
import joblib

C:\Users\vncpyy7h\AppData\Local\Temp\ipykernel_12500\3224888460.py:39: DeprecationWarning: Importing context_recall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import context_recall
  from ragas.metrics import (
C:\Users\vncpyy7h\AppData\Local\Temp\ipykernel_12500\3224888460.py:39: DeprecationWarning: Importing context_precision from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import context_precision
  from ragas.metrics import (
C:\Users\vncpyy7h\AppData\Local\Temp\ipykernel_12500\3224888460.py:39: DeprecationWarning: Importing answer_correctness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import answer_correctness
  from ragas.metrics import (
C:\Users\vncpyy7h\AppData\Local\Temp\ipykernel_12500\3224888460.py:39: DeprecationWarning: Importing answer_similarity from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import answer_similarity
  from ragas.metrics import (

In [2]:
pd.set_option('display.max_colwidth', None)

## Retrieval and integrate with LLM

In [ ]:

# --- Configuration ---
QDRANT_URL = "your_qdrant_url"  # Replace with your actual Qdrant URL
QDRANT_API_KEY = "your_qdrant_api_key"  # Replace with your actual Qdrant API key
COLLECTION_NAME = "banking_faq"
OPENAI_API_KEY = "your_openai_api_key"  # Replace with your actual OpenAI API key
MODEL_DIR = "./"

# Initialize Clients
client = QdrantClient(url=QDRANT_URL, api_key=QDRANT_API_KEY)
# Initialize your BankingClassifier class (from your previous code)
bot = BankingClassifier(model_dir=MODEL_DIR)
bot.load() # This loads the encoder and intent classifier

# Initialize OpenAI
openai_client = OpenAI(api_key=OPENAI_API_KEY)
# 1. Set your OpenAI API key for Ragas
os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY

--- Initializing Classifier ---

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading complete in 10.91 seconds.

In [4]:
sparse_encoder = SparseTextEmbedding(model_name="prithivida/Splade_PP_en_v1")

In [ ]:
from qdrant_client import models

def get_banking_answer(user_query, use_hybrid=False):

    # 1. Blocklist Guardrail (Fast, low-cost)
    RISK_KEYWORDS = [r"invest", r"crypto", r"bitcoin", r"hack", r"launder"]
    if any(re.search(word, user_query.lower()) for word in RISK_KEYWORDS):
        return {"answer": "I cannot assist with that request as it falls outside my banking policy.", "category": "BLOCKED"}
    # 1. Classify the CATEGORY
    category, conf, latency = bot.predict(user_query)
    
    # 2. Embed the query
    query_vector = bot.encoder.encode(user_query).tolist()
    sparse_vector = None

    # Define the Category Filter
    filter_condition = models.Filter(
        must=[models.FieldCondition(key="category", match=models.MatchValue(value=category))]
    )

    # --- HYBRID SEARCH LOGIC ---
    if use_hybrid:
        # Generate Sparse (Keyword) Vector
        sparse_vector = list(sparse_encoder.embed(user_query))[0] # Example for fastembed
        # For this example, let's assume sparse_vector is ready
        
        prefetch = [
            models.Prefetch(query=query_vector, using="dense", limit=10, filter=filter_condition),
            models.Prefetch(query=sparse_vector, using="sparse", limit=10, filter=filter_condition)
        ]
        
        search_results = client.query_points(
            collection_name="banking_faq",
            prefetch=prefetch,
            query=models.FusionQuery(fusion=models.Fusion.RRF),
            limit=1
        )
    
    # --- PURE VECTOR SEARCH LOGIC (Original) ---
    else:
        search_results = client.query_points(
            collection_name="banking_faq",
            query=query_vector,
            query_filter=filter_condition,
            limit=1
        )
    
    # 3. Handle Results
    if search_results.points:
        best_match = search_results.points[0].payload
        return {
            "answer": best_match['answer'],
            "category": category,
            "confidence": conf
        }
    else:
        # Fallback Logic (Repeat same process but without filter)
        print("No match in category, searching entire database...")
        
        if use_hybrid:
            prefetch = [
                models.Prefetch(query=query_vector, using="dense", limit=10),
                models.Prefetch(query=sparse_vector, using="sparse", limit=10)
            ]
            fallback_results = client.query_points(
                collection_name="banking_faq",
                prefetch=prefetch,
                query=models.FusionQuery(fusion=models.Fusion.RRF),
                limit=1
            )
        else:
            fallback_results = client.query_points(
                collection_name="banking_faq",
                query=query_vector,
                limit=1
            )
            
        if fallback_results.points:
            return {
                "answer": fallback_results.points[0].payload['answer'],
                "category": "GENERAL"
            }
        else:
            return {"answer": "I'm sorry, I don't know.", "category": "GENERAL"}

In [6]:
get_banking_answer('I got to activate a card , can you help me?')

{'answer': 'I\'m happy to help! I\'d be happy to assist you with activating your card. To get started, please follow these steps:\n\n1. Download and install our mobile app from the App Store or Google Play Store.\n2. Open the app and sign in to your account.\n3. Navigate to the "Cards" section or a similar option.\n4. Look for the option to activate a new card.\n5. Enter the necessary information such as the card number, expiration date, and CVV.\n6. Follow the on-screen prompts to complete the activation process.\n\nIf you encounter any difficulties during the activation process or have any questions, please don\'t hesitate to reach out to our customer support team at {{Customer Support Phone Number}}. They\'re available {{Customer Support Working Hours}} to assist you further. Enjoy using your activated card!',
 'category': 'CARD',
 'confidence': 0.9999811830568314}

In [8]:
def get_banking_answer_with_llm(user_query):
    # 1. Retrieve the data (using your existing logic)
    data = get_banking_answer(user_query) # This returns the dict with 'answer' and 'category'
    
    if data['answer'] == "I'm sorry, I don't know.":
        return data['answer']
    #print(data['answer'])
    # 2. Construct the Prompt for GPT-4o-mini
    prompt = f"""
    You are a banking support assistant. 
    Your ONLY source of information is the "KNOWLEDGE BASE" provided below. 
    
    RULES:
    1. STRICT ADHERENCE: You must use the steps provided in the KNOWLEDGE BASE exactly as they appear. 
    2. NO FABRICATION: Do not add steps, do not remove steps, and do not change the terminology (e.g., if it says 'Forgot Password', do not say 'Sign In').
    3. FORMATTING: Output the response in a clear, numbered list format.
    4. ALIGNMENT: If the KNOWLEDGE BASE is missing a step, do not invent one. State that the instructions are as provided.

    KNOWLEDGE BASE:
    {data['answer']}

    USER QUESTION:
    {user_query}

    RESPONSE:
    """

    # 3. Call GPT-4o-mini
    response = openai_client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": "You are a helpful banking assistant."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.1 # Lower temperature = more factual, less creative
    )

    return response.choices[0].message.content

In [9]:
# --- Test it ---
final_answer = get_banking_answer_with_llm("I make a mistake, how could I cancel a bank transfer?")
print(final_answer)

1. First, log in to your online banking account or mobile banking app.

2. Navigate to the section that displays your recent transactions or transfers.

3. Locate the specific bank transfer that you want to cancel. Look for options such as "Cancel," "Reverse," or "Undo" next to the transaction.

4. If you don't see any direct cancellation options, you can contact your bank's customer support service through their hotline or online chat. They will guide you through the cancellation process and provide any additional steps or requirements.

5. It's important to act as soon as possible to increase the chances of successfully canceling the transfer. Transfers that have already been processed may be more difficult to cancel.

Remember, every bank may have slightly different procedures, so it's best to follow the instructions provided by your specific bank. If you have any further questions or need additional assistance, please let me know.

### Groundedness evaluation
- The reponse should have enough information. For banking products, missing or adding things are unacceptable  
- It checks results from vector database retrieval

In [10]:
#dataset = load_dataset("bitext/Bitext-retail-banking-llm-chatbot-training-dataset", split="train")

In [12]:
# 3. Initialize the stronger evaluator LLM (gpt-4o-mini is highly recommended for Ragas)
evaluator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4o-mini", temperature=0))

# 4. Load the specific retail banking dataset
print("Loading banking dataset from Hugging Face...")
raw_dataset = load_dataset("bitext/Bitext-retail-banking-llm-chatbot-training-dataset", split="train")

# 5. Select a small subset to evaluate (e.g., 50 rows) to manage costs and speed
EVAL_SAMPLE_SIZE = 100
eval_subset = raw_dataset.shuffle(seed=1).select(range(EVAL_SAMPLE_SIZE))

# 6. Lists to collect data for Ragas
questions = []
contexts = []      # Must be a list of lists of strings
ground_truths = []

# Define the regex pattern to match anything inside {{ }}
placeholder_pattern = r'\{\{.*?\}\}'


def unwrap_placeholders(text):
    """
    Dynamically removes the double curly braces {{ and }} but keeps the 
    inner text intact. This maintains grammatical completeness with zero hardcoding.
    """
    if not isinstance(text, str):
        return text
    return re.sub(r'\{\{(.*?)\}\}', r'\1', text)


print(f"Starting retrieval process for {EVAL_SAMPLE_SIZE} samples...")

# ==========================================
# Step 1: The Retrieval Loop (Populates & Cleans the lists)
# ==========================================
for index, row in enumerate(eval_subset):
    query = row["instruction"]      # The user's question
    expected_truth = row["response"] # The gold standard answer
    
    print(f"[{index + 1}/{EVAL_SAMPLE_SIZE}] Retrieving for: '{query[:50]}...'")
    
    # Run your Qdrant retrieval function
    try:
        retrieved_data = get_banking_answer(query)
        retrieved_context = retrieved_data["answer"]
        
        # --- Context Cleaning Logic ---
        if isinstance(retrieved_context, str):
            # A. Clean string-wrapped lists: "['text']" -> "text"
            if retrieved_context.startswith("['") and retrieved_context.endswith("']"):
                try:
                    parsed_list = ast.literal_eval(retrieved_context)
                    if isinstance(parsed_list, list) and len(parsed_list) > 0:
                        retrieved_context = parsed_list[0]
                except Exception:
                    retrieved_context = retrieved_context.strip("[]'\"").replace("\\'", "'")
            
            # B. Clean literal backslash escapes
            retrieved_context = retrieved_context.replace('\\n', '\n').replace('""', '"').strip()
            expected_truth = expected_truth.strip()
            
            # C. DYNAMIC UNWRAPPING: Keep the noun, strip only the braces
            retrieved_context = unwrap_placeholders(retrieved_context)
            expected_truth = unwrap_placeholders(expected_truth)
            
            # D. Clean up any accidental double spaces left behind
            retrieved_context = re.sub(r'\s+', ' ', retrieved_context).strip()
            expected_truth = re.sub(r'\s+', ' ', expected_truth).strip()
                
    except Exception as e:
        print(f"Error retrieving for query '{query}': {e}")
        retrieved_context = "Error during retrieval"

    # Append to our evaluation datasets
    questions.append(query)
    contexts.append([retrieved_context]) 
    ground_truths.append(expected_truth)


# ==========================================
# Step 2: Batch Ragas Evaluation
# ==========================================
print(f"\nInitiating Batch Ragas evaluation for {EVAL_SAMPLE_SIZE} samples...")

# Construct the full batch dataset
eval_data = {
    "question": questions,
    "contexts": contexts,
    "ground_truth": ground_truths
}
ragas_dataset = Dataset.from_dict(eval_data)

# Configure the run to use 2 parallel workers to prevent rate limits or hanging
config = RunConfig(max_workers=2, timeout=60.0)

try:
    # Run evaluation on the entire batch at once
    results = evaluate(
        dataset=ragas_dataset,
        metrics=[context_recall, context_precision],
        run_config=config,
        llm=evaluator_llm  # Force Ragas to use gpt-4o-mini instead of gpt-3.5-turbo
    )
    
    # --- FINAL RESULTS DISPLAY ---
    
    print("\n=== OVERALL RETRIEVAL AVERAGE SCORES ===")
    print(results)

    # Convert the results to a Pandas DataFrame to view the individual details
    df_results = results.to_pandas()
    
    print("\n=== DETAILED BREAKDOWN PER QUERY ===")
    display(df_results[['user_input', 'retrieved_contexts', 'reference', 'context_recall', 'context_precision']])

except Exception as e:
    print(f"\nBatch evaluation failed: {e}")

C:\Users\vncpyy7h\AppData\Local\Temp\ipykernel_4196\3839465065.py:2: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  evaluator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4o-mini", temperature=0))

Loading banking dataset from Hugging Face...
Starting retrieval process for 100 samples...
[1/100] Retrieving for: 'i cant find my accfount fees i need help checking ...'
[2/100] Retrieving for: 'I have made a mistake and I transferred money to t...'
[3/100] Retrieving for: 'can I see the loan payment?...'
[4/100] Retrieving for: 'i have to see the mortgage payments how could i do...'
[5/100] Retrieving for: 'i cannot pay for my loan help me canceling it...'
[6/100] Retrieving for: 'I need help to see the current balance on my cards...'
[7/100] Retrieving for: 'I want to send money, ia it possible to perform a ...'
[8/100] Retrieving for: 'wanna check the  fucking card annual fee i need as...'
[9/100] Retrieving for: 'i dont have a fucking profile can ya help me creat...'
[10/100] Retrieving for: 'I'm looking for a mortgaeg...'
[11/100] Retrieving for: 'i got to check my fees can uhwlp me...'
[12/100] Retrieving for: 'I can't find my fucking card annual fee, I need as...'
[13/100] Retrieving for: 'I need to get back a swallowed card by an ATM , ca...'
[14/100] Retrieving for: 'could ya help me to see the loan payments...'
[15/100] Retrieving for: 'I would like to cancel a fucking bank transfer , w...'
[16/100] Retrieving for: 'can  you help me to apply for a mortgage?...'
[17/100] Retrieving for: 'I hve to send an email to fucking customer support...'
[18/100] Retrieving for: 'can you tell me more about my fucking recent trans...'
[19/100] Retrieving for: 'I am looking  for information about a branch in my...'
[20/100] Retrieving for: 'I got to see the loan  payments, I need help...'
[21/100] Retrieving for: 'wanna cancel a bank transfer can ya help me...'
[22/100] Retrieving for: 'i need information about the fucking credit card a...'
[23/100] Retrieving for: 'i have to chewck the loan payment help me...'
[24/100] Retrieving for: 'im travelling overseas how do i activate a master ...'
[25/100] Retrieving for: 'i cannot find my visa i need assistanec locking it...'
[26/100] Retrieving for: 'I would like to find the closest branhc, help me...'
[27/100] Retrieving for: 'I want to check the mortgage payment, help me...'
[28/100] Retrieving for: 'I'm traveling overseas I'd like to activate a visa...'
[29/100] Retrieving for: 'id like to cancel a loan...'
[30/100] Retrieving for: 'wanna cancel a loan where do i do i...'
[31/100] Retrieving for: 'i do not wanna pay for my loan help me to cancel i...'
[32/100] Retrieving for: 'I don't have a fucking account, could you help me ...'
[33/100] Retrieving for: 'I got to activate a Master Card...'
[34/100] Retrieving for: 'I made a mistake and I have transferred money to t...'
[35/100] Retrieving for: 'wanns send money to someone i need assistance to m...'
[36/100] Retrieving for: 'need to block an amex online how can i do it...'
[37/100] Retrieving for: 'wanna find the nearest atm i need hlp...'
[38/100] Retrieving for: 'I'd like to block an credit card on mobile, can yo...'
[39/100] Retrieving for: 'I'd like to know about my fees...'
[40/100] Retrieving for: 'wanna check the <fucking> current balance of my ba...'
[41/100] Retrieving for: 'acn I search for an ATM near?...'
[42/100] Retrieving for: 'I'd like to check the fucking card annual fees, wh...'
[43/100] Retrieving for: 'i dont understnd ui need assistance talking to a p...'
[44/100] Retrieving for: 'i have to cancel an fucking bank transfer to a con...'
[45/100] Retrieving for: 'i got to check the loan payment how do i do it...'
[46/100] Retrieving for: 'I want to send money to someone, how do I perform ...'
[47/100] Retrieving for: 'can ya help me see the fucking bank statement...'
[48/100] Retrieving for: 'i cant pay for my mortgage can uhelp me cancel it...'
[49/100] Retrieving for: 'need to send an email to customer service will ya ...'
[50/100] Retrieving for: 'I don't want to pay for my loan, could youhelp me ...'
[51/100] Retrieving for: 'i want assistanec to cancel a loan...'
[52/100] Retrieving for: 'I want to apply for a loan, I need help...'
[53/100] Retrieving for: 'I would like to cancel a Master Card on mobile, co...'
[54/100] Retrieving for: 'I got to dispute an ATM withdrawal, could I get so...'
[55/100] Retrieving for: 'I got to close a fucking user account, how do I do...'
[56/100] Retrieving for: 'wanna send money to someone online how could i mak...'
[57/100] Retrieving for: 'I'd like to activate an amex for international usa...'
[58/100] Retrieving for: 'id like ot apply for a mortgage i need assistance...'
[59/100] Retrieving for: 'id liek to close a fucking online account will uhe...'
[60/100] Retrieving for: 'I have to disputea withdrawal...'
[61/100] Retrieving for: 'I made a mistake, help me canceling a bank transfe...'
[62/100] Retrieving for: 'wanna check the <fucking> current balance of my ba...'
[63/100] Retrieving for: 'I got to check the current balance on my card, whe...'
[64/100] Retrieving for: 'i got to activate a master card on mobile how to d...'
[65/100] Retrieving for: 'i got to see the mortagge payments how to do it...'
[66/100] Retrieving for: 'I can't pay for my mortgage, help me t cancel it...'
[67/100] Retrieving for: 'I can't pay for my loan, can I cancel it ?...'
[68/100] Retrieving for: 'i want assistance activating a credit cardd online...'
[69/100] Retrieving for: 'wanna send money to someone I'd like to make a tra...'
[70/100] Retrieving for: 'I would like to see the mortgage payment, could I ...'
[71/100] Retrieving for: 'i want help  canceling a loan...'
[72/100] Retrieving for: 'I'd like to speak with a fucking operator, how can...'
[73/100] Retrieving for: 'I want ti open a fucking user account...'
[74/100] Retrieving for: 'would ti be possible to cancel a visa on mobile...'
[75/100] Retrieving for: 'I want to know about the fucking current balance o...'
[76/100] Retrieving for: 'I got to retrieve a credit card  by an ATM, how do...'
[77/100] Retrieving for: 'I want to talk to customer support, where could I ...'
[78/100] Retrieving for: 'i got to see the fuccking recent transaction detai...'
[79/100] Retrieving for: 'I want to see the loan payments, how to do it ?...'
[80/100] Retrieving for: 'the ATM did not return my credit card, how can I g...'
[81/100] Retrieving for: 'i got to activate a amex for international usage c...'
[82/100] Retrieving for: 'I don't want to pay for my loan, could you cancel ...'
[83/100] Retrieving for: 'I am trying to find a loan, can you help me?...'
[84/100] Retrieving for: 'how could i activate an card on mobile...'
[85/100] Retrieving for: 'id like to see the current balance of my bank acco...'
[86/100] Retrieving for: 'there is a withdrawalo i didnt make what can i do...'
[87/100] Retrieving for: 'need to check the fucking recent transaction detai...'
[88/100] Retrieving for: 'my card has been stolen, I want to block it?...'
[89/100] Retrieving for: 'I need to regster an online account...'
[90/100] Retrieving for: 'i cant find my account fees can uhelp me checking ...'
[91/100] Retrieving for: 'where could I cancel a loan?...'
[92/100] Retrieving for: 'I have to locfk a card, will you help me?...'
[93/100] Retrieving for: 'I need to check the mortgage payment, will you hel...'
[94/100] Retrieving for: 'i need cash how to search for a branch...'
[95/100] Retrieving for: 'I am looking for information about the nearest bra...'
[96/100] Retrieving for: 'I would like to cancel a fucking profile , how do ...'
[97/100] Retrieving for: 'i cannot pay for my loan i need assistance to canc...'
[98/100] Retrieving for: 'wanna activate a visa on mobile how can i do it...'
[99/100] Retrieving for: 'need to set up an password where can i do it...'
[100/100] Retrieving for: 'where can I check the card annuals fees?...'

Initiating Batch Ragas evaluation for 100 samples...

Evaluating:   0%|          | 0/200 [00:00<?, ?it/s]

=== OVERALL RETRIEVAL AVERAGE SCORES ===
{'context_recall': 0.9796, 'context_precision': 0.9900}

=== DETAILED BREAKDOWN PER QUERY ===

,user_input,retrieved_contexts,reference,context_recall,context_precision
0,i cant find my accfount fees i need help checking them,"[I'm genuinely sorry for the inconvenience you're experiencing in locating your account fees. I'm here to help you with that. To check your account fees, please follow these steps: 1. Log in to your account on our website. 2. Navigate to the ""Account"" or ""Profile"" section. 3. Look for an option like ""View Account Fees"" or ""Billing Information"". 4. Click on that option to access detailed information about your account fees. If you're unable to locate the account fees or need further assistance, please provide me with your account details or any other relevant information, and I'll gladly assist you further.]","I'm genuinely sorry for the inconvenience you're experiencing in locating your account fees. I'm here to help you with that. To check your account fees, please follow these steps: 1. Log in to your account on our website. 2. Navigate to the ""Account"" or ""Profile"" section. 3. Look for an option like ""View Account Fees"" or ""Billing Information"". 4. Click on that option to access detailed information about your account fees. If you're unable to locate the account fees or need further assistance, please provide me with your account details or any other relevant information, and I'll gladly assist you further.",1.000000,1.0
1,"I have made a mistake and I transferred money to the wrong account, could you help me cancelling a transfer?","[Please accept my apologies for any inconvenience caused by the mistaken bank transfer. I understand how important it is to resolve this issue for you. Rest assured, I'm here to help you cancel the transfer to the wrong account. To proceed with canceling the transfer, we'll need some specific details. Please provide me with the following information: 1. Your Name: So I can verify your account details. 2. Date and time of the transfer: This will assist in locating the transaction. 3. The amount and currency transferred: This helps identify the specific transaction among others. Once I have these details, I'll escalate the issue to our support team, who will take the necessary steps to cancel the transfer. Please note that depending on the circumstances, cancellation may not always be guaranteed. However, we'll do everything we can to assist you. If you have any additional questions or concerns, feel free to let me know. We're here to provide you with the support you need.]","Please accept my apologies for any inconvenience caused by the mistaken bank transfer. I understand how important it is to resolve this issue for you. Rest assured, I'm here to help you cancel the transfer to the wrong account. To proceed with canceling the transfer, we'll need some specific details. Please provide me with the following information: 1. Your Name: So I can verify your account details. 2. Date and time of the transfer: This will assist in locating the transaction. 3. The amount and currency transferred: This helps identify the specific transaction among others. Once I have these details, I'll escalate the issue to our support team, who will take the necessary steps to cancel the transfer. Please note that depending on the circumstances, cancellation may not always be guaranteed. However, we'll do everything we can to assist you. If you have any additional questions or concerns, feel free to let me know. We're here to provide you with the support you need.",1.000000,1.0
2,can I see the loan payment?,"[I'd be happy to assist you in checking your loan payment. To view your loan payment details, you can log in to your account on our website or mobile app. Once you're logged in, navigate to the ""Loan"" or ""Account"" section, where you should be able to find the information you need. If you encounter any issues or have trouble locating the payment details, please let me know, and I'll guide you through the process.]","I'd be happy to assist you in checking your loan payment. To view your loan payment details, you can log in to your account on our website or mobile app. Once you're logged in, navigate to the ""Loan"" or ""Account"" section, where you should be able to find the information you need. If you encounter any issues or have trouble locating the payment details, please let me know, and I'll guide you through the process.",1.000000,1.0
3,i have to see the mortgage payments how could i do it,"[I'm here to help you check your mortgage payments. Here's what you can do: 1. Login to your Online Banking account. 2. Navigate to the Mortgage Payments section. 3. Look for an option like ""View Mortgage Payments"" or ""Payment History"". 4. Click on it to access the details of your mortgage payments. If you need further assistance or encounter any difficulties, feel free to let me know. I'm here to assist you every step of the way!]","I'm here to help you check your mortgage payments. Here's what you can do: 1. Login to your Online Banking account. 2. Navigate to the Mortgage Payments section. 3. Look for an option like ""View Mortgage Payments"" or ""Payment History"". 4. Click on it to access the details of your mortgage payments. If you need further assistance or encounter any difficulties, feel free to let me know. I'm here to assist you every step of the way!",1.000000,1.0
4,i cannot pay for my loan help me canceling it,"[I'm sorry to hear that you're facing difficulty in paying for your loan. I'm here to help you with canceling it. To initiate the cancellation process, please follow these steps: 1. Contact our customer support team at Customer Support Phone Number or email us at Customer Support Email Address and explain your situation. They will guide you through the cancellation process and provide you with the necessary instructions. 2. Make sure to provide them with your loan details and any relevant information, such as your loan account number or loan agreement number. This will assist them in locating your loan and processing the cancellation request more efficiently. 3. If needed, our customer support team might require additional documentation or information from you to complete the cancellation process. Please be prepared to provide any requested documents promptly. 4. Once your cancellation request has been processed, you will receive confirmation along with any further instructions or actions you need to take. If you have any further questions or concerns, please don't hesitate to reach out to our customer support team. They are available to assist you and provide further guidance throughout the cancellation process.]","I'm sorry to hear that you're facing difficulty in paying for your loan. I'm here to help you with canceling it. To initiate the cancellation process, please follow these steps: 1. Contact our customer support team at Customer Support Phone Number or email us at Customer Support Email Address and explain your situation. They will guide you through the cancellation process and provide you with the necessary instructions. 2. Make sure to provide them with your loan details and any relevant information, such as your loan account number or loan agreement number. This will assist them in locating your loan and processing the cancellation request more efficiently. 3. If needed, our customer support team might require additional documentation or information from you to complete the cancellation process. Please be prepared to provide any requested documents promptly. 4. Once your cancellation request has been processed, you will receive confirmation along with any further instructions or actions you need to take. If you have any further questions or concerns, please don't hesitate to reach out to our customer support team. They are available to assist you and provide further guidance throughout the cancellation process.",1.000000,1.0
...,...,...,...,...,...
95,"I would like to cancel a fucking profile , how do I do it?","[I understand the inconvenience, and I'm sorry for any frustration or inconvenience you may have encountered with your user account. I understand that you would like to cancel your profile. I'm here to assist you with that. To cancel your profile, please follow these steps: 1. Log in to your account on our website. 2. Navigate to your account settings or profile settings. 3. Look for the option to cancel or delete your profile. 4. Follow the provided instructions to confirm the cancellation. If you encounter any difficulties or need further assistance during the process, please don't hesitate to reach out to our customer support team. We're available Customer Support Working Hours at Customer Support Phone Number or you can chat with us through the Live Chat function on our website at Company Website URL. We appreciate your understanding and we're here to help ensure a smooth cancellation process for you.]","I understand the inconvenience, and I'm sorry for any frustration or inconvenience you may have encountered with your user account. I understand that you would like to cancel your profile. I'm here to assist you with that. To cancel your profile, please follow these steps: 1. Log in to your account on our website. 2. Navigate to your account settings or profile settings. 3. Look for the option to cancel or delete your profile. 4. Follow the provided instructions to confirm the cancellation. If you encounter any difficulties or need further assistance during the process, please don't hesitate to reach out to our customer support team. We're available Customer Support Working Hours at Customer Support Phone Number or you can chat with us through the Live Chat function on our website at Company Website URL. We appreciate your understanding and we're here to help ensure a smooth cancellation process for you.",0.714286,1.0
96,i cannot pay for my loan i need assistance to cancel it,"[I'm sorry to hear that you're experiencing difficulties making payments for your loan. I understand that canceling the loan may be a viable option for you. Let's work together to find a solution. Before we proceed with canceling your loan, I suggest reaching out to our dedicated Loan Support Team. They are equipped to offer personalized assistance that aligns with your specific situation. They can explore potential alternatives, such as adjusting the payment plan or offering temporary relief options. To contact our Loan Support Team, you can reach them at Loan Support Phone Number or via email at Loan Support Email Address. They'll be more than happy to provide guidance and support in canceling your loan if necessary. Remember, we're here to help and find the best outcome for you. Let me know if there's anything else I can assist you with.]","I'm sorry to hear that you're experiencing difficulties making payments for your loan. I understand that canceling the loan may be a viable option for you. Let's work together to find a solution. Before we proceed with canceling your loan, I suggest reaching out to our dedicated Loan Support Team. They are equipped to offer personalized assistance that aligns with your specific situation. They can explore potential alternatives, such as adjusting the payment plan or offering temporary relief options. To contact our Loan Support Team, you can reach them at Loan Support Phone Number or via email at Loan Support Email Address. They'll be more than happy to provide guidance and support in canceling your loan if necessary. Remember, we're here to help and find the best outcome for you. Let me know if there's anything else I can assist you with.",1.000000,1.0
97,wanna activate a visa on mobile how can i do it,"[I can help you activate your Credit Card on your mobile device. Activating a Credit Card on mobile is a quick and easy process. Here's what you need to do: 1. Download the mobile banking app of your card issuer from your device's app store. 2. Open the app and log in to your account using your credentials. 3. Look for the ""Manage Cards"" or ""My Cards"" section within the app. 4. Find your Credit Card from the list of cards associated with your account. 5. Select the option to activate the card. 6. Follow the on-screen instructions to complete the activation process. This may involve entering the card details or verifying your identity. 7. Once the activation is successful, you will receive a confirmation message. If you encounter any difficulties during the activation process or have any further questions, please don't hesitate to reach out. I'm here to assist you every step of the way!]","I can help you activate your Credit Card on your mobile device. Activating a Credit Card on mobile is a quick and easy process. Here's what you need to do: 1. Download the mobile banking app of your card issuer from your device's app store. 2. Open the app and log in to your account using your credentials. 3. Look for the ""Manage Cards"" or ""My Cards"" section within the app. 4. Find your Credit Card from the list of cards associated with your account. 5. Select the option to activate the card. 6. Follow the on-screen instructions to complete the activation process. This may involve entering the card details or verifying your identity. 7. Once the activation is successful, you will receive a confirmation message. If you encounter any difficulties during the activation process or have any further questions, please don't hesitate to reach out. I'm here to assist you every step of the way!",1.000000,1.0
98,need to set up an password where can i do it,"[I'm happy to help! I can assist you in setting up a password for your account. Here's what you need to do: 1. Go to the ""Account Settings"" or ""Profile"" section on our website. 2. Look for the ""Password"" or ""Security"" tab. 3. Click on the tab and you'll be directed to the password setup page. 4. Follow the instructions to create a strong and secure password. Make sure it meets the required criteria (e.g., a mix of uppercase and lowercase letters, numbers, and special characters). 5. Once you've entered and confirmed your new password, click on the ""Save"" or ""Update"" button. If you encounter any difficulties or have any questions during the process, please don't hesitate to let me know. I'm here to make it as smooth as possible for you!]","I'm happy to help! I can assist you in setting up a password for your account. Here's what you need to do: 1. Go to the ""Account Settings"" or ""Profile"" section on our website. 2. Look for the ""Password"" or ""Security"" tab. 3. Click on the tab and you'll be directed to the password setup page. 4. Follow the instructions to create a strong and secure password. Make sure it meets the required criteria (e.g., a mix of uppercase and lowercase letters, numbers, and special characters). 5. Once you've entered and confirmed your new password, click on the ""Save"" or ""Update"" button. If you encounter any difficulties or have any questions during the process, please don't hesitate to let me know. I'm here to make it as smooth as possible for you!",1.000000,1.0
99,where can I check the card annuals fees?,"[I can assist you with that. To find the information about your card's annual fees, you have a few options: 1. Online Banking: If you have access to online banking, simply log in to your account on our website or mobile app. Navigate to the credit card section, where you should find a summary of your card details, including the annual fees. 2. Customer Service: Our knowledgeable customer service representatives are available to help you. You can reach them through our dedicated helpline at Customer Support Phone Number. They will be happy to provide you with the necessary information about the annual fees for your card. 3. Card Statement: The annual fees for your card are usually mentioned on your monthly card statement. Take a look at the ""Fees and Charges"" or ""Summary"" section, where you should find the details you're looking for. If you encounter any difficulties or need further assistance, please feel free to let me know. I'm here to help!]","I can assist you with that. To find the information about your card's annual fees, you have a few options: 1. Online Banking: If you have access to online banking, simply log in to your account on our website or mobile app. Navigate to the credit card section, where you should find a summary of your card details, including the annual fees. 2. Customer Service: Our knowledgeable customer service representatives are available to help you. You can reach them through our dedicated helpline at Customer Support Phone Number. They will be happy to provide you with the necessary information about the annual fees for your card. 3. Card Statement: The annual fees for your card are usually mentioned on your monthly card statement. Take a look at the ""Fees and Charges"" or ""Summary"" section, where you should find the details you're looking for. If you encounter any difficulties or need further assistance, please feel free to let me know. I'm here to help!",1.000000,1.0

In [13]:
df_results.columns

Index(['user_input', 'retrieved_contexts', 'reference', 'context_recall',
       'context_precision'],
      dtype='str')

In [14]:
raw_dataset.filter(lambda example: example['instruction'] == 'show me the loan payments')['response']

Column(['I\'ll do my best! I can help you with that. Checking your loan payments is a breeze. Here\'s what you need to do:\n\n1. Log in to your account on our website or app.\n2. Navigate to the "Loan" section or "My Loans" tab.\n3. Look for the "Payments" or "Payment History" option.\n4. Click on it to access your loan payment details.\n\nThere, you\'ll find a comprehensive record of your loan payments, including the due dates, amounts paid, and any outstanding balances. If you need further assistance or have any questions regarding your loan payments, feel free to reach out to our customer support team at {{Customer Support Phone Number}} or through the Live Chat on our website at {{Company Website URL}}. We\'re here to ensure a smooth loan payment experience for you.'])

In [15]:
df_results[['user_input','retrieved_contexts','reference','context_recall','context_precision']].sort_values(by='context_recall')

,user_input,retrieved_contexts,reference,context_recall,context_precision
70,i want help canceling a loan,"[Certainly, I can assist you with canceling your loan. I understand that canceling a loan can be a significant decision, and I'm here to guide you through the process. To cancel your loan, please follow these steps: 1. Contact our customer support team at Customer Support Phone Number or through our Live Chat service on our website at Company Website URL. They will be able to provide you with the necessary guidance and assist you with canceling your loan. 2. Prepare any relevant information or documentation related to your loan, such as your loan account number or any supporting documents you may have. 3. When contacting our customer support team, clearly explain your intention to cancel the loan. They may ask you for specific details to verify your identity and locate your loan account. 4. Once the cancellation process is initiated, our customer support team will guide you through the next steps, which may include filling out a cancellation form or providing additional information. 5. Take note of any confirmation numbers or reference numbers provided by our customer support team. This will serve as proof of your loan cancellation. If you have any further questions or require additional assistance, please don't hesitate to reach out. We're here to help you throughout the cancellation process.]","I'm sorry to hear that you're looking to cancel a loan. I'll do my best to assist you with that. To cancel your loan, please follow these steps: 1. Contact our customer support team at Customer Support Phone Number or email us at Customer Support Email Address. They will guide you through the cancellation process and provide any necessary forms or documentation. 2. Make sure to have your loan details ready, such as the loan account number, loan amount, and any applicable identification information. 3. Depending on the type of loan, there may be specific terms and conditions for cancellation. Our customer support team will be able to provide you with all the necessary information. 4. It's important to note that there may be fees or penalties associated with loan cancellations. Our customer support team will inform you of any applicable charges. If you have any further questions or need assistance, feel free to reach out to our customer support team. We're here to help make this process as smooth as possible for you.",0.272727,1.0
39,wanna check the <fucking> current balance of my bank account were can i do it,"[Certainly, I can assist you with that! Checking your current balance is an essential part of managing your bank account effectively. Here's how you can do it: 1. Log in to your online banking portal or mobile banking app. 2. Navigate to the ""Account Summary"" or ""Balances"" section. 3. You should be able to see your current account balance displayed there. 4. If you can't find it, look for options like ""My Accounts"" or ""Account Details"" and select the specific account you want to check the balance for. 5. If you're still having trouble finding the balance, reach out to our customer support team at Customer Support Phone Number. They will be more than happy to assist you. Remember, keeping track of your current balance regularly is a great way to stay informed about your financial standing. If you have any further questions or need assistance with anything else, feel free to let me know!]","Certainly, I can assist you with that! Checking your current balance is an essential part of managing your bank account effectively. Here's how you can do it: 1. Log in to your online banking portal or mobile banking app. 2. Navigate to the ""Account Summary"" or ""Balances"" section. 3. You should be able to see your current account balance displayed there. 4. If you can't find it, look for options like ""My Accounts"" or ""Account Details"" and select the specific account you want to check the balance for. 5. If you're still having trouble finding the balance, reach out to our customer support team at Customer Support Phone Number. They will be more than happy to assist you. Remember, keeping track of your current balance regularly is a great way to stay informed about your financial standing. If you have any further questions or need assistance with anything else, feel free to let me know!",0.700000,1.0
95,"I would like to cancel a fucking profile , how do I do it?","[I understand the inconvenience, and I'm sorry for any frustration or inconvenience you may have encountered with your user account. I understand that you would like to cancel your profile. I'm here to assist you with that. To cancel your profile, please follow these steps: 1. Log in to your account on our website. 2. Navigate to your account settings or profile settings. 3. Look for the option to cancel or delete your profile. 4. Follow the provided instructions to confirm the cancellation. If you encounter any difficulties or need further assistance during the process, please don't hesitate to reach out to our customer support team. We're available Customer Support Working Hours at Customer Support Phone Number or you can chat with us through the Live Chat function on our website at Company Website URL. We appreciate your understanding and we're here to help ensure a smooth cancellation process for you.]","I understand the inconvenience, and I'm sorry for any frustration or inconvenience you may have encountered with your user account. I understand that you would like to cancel your profile. I'm here to assist you with that. To cancel your profile, please follow these steps: 1. Log in to your account on our website. 2. Navigate to your account settings or profile settings. 3. Look for the option to cancel or delete your profile. 4. Follow the provided instructions to confirm the cancellation. If you encounter any difficulties or need further assistance during the process, please don't hesitate to reach out to our customer support team. We're available Customer Support Working Hours at Customer Support Phone Number or you can chat with us through the Live Chat function on our website at Company Website URL. We appreciate your understanding and we're here to help ensure a smooth cancellation process for you.",0.714286,1.0
91,"I have to locfk a card, will you help me?","[I'm here to assist you with blocking your card. I understand the importance of this matter and I'll guide you through the process. To block your card, please follow these steps: 1. Contact our Customer Support Team immediately, either through our website or by calling Customer Support Phone Number. 2. Provide the agent with your card details, such as the card number or account information, to verify your identity. 3. Explain that you want to block the card and the reason behind it, such as suspected fraudulent activity or loss of the card. 4. The customer support representative will assist you further and initiate the blocking process. 5. If necessary, they will also guide you on the next steps, such as ordering a replacement card or disputing any unauthorized transactions. Remember, time is of the essence when it comes to card security, so please don't delay in reaching out to our customer support team. They are available Customer Support Working Hours to help you promptly and ensure the safety of your account. Rest assured, we're here to support you in any way we can. If you have any additional questions or concerns, feel free to let me know.]","I'm here to assist you with blocking your card. I understand the importance of this matter and I'll guide you through the process. To block your card, please follow these steps: 1. Contact our Customer Support Team immediately, either through our website or by calling Customer Support Phone Number. 2. Provide the agent with your card details, such as the card number or account information, to verify your identity. 3. Explain that you want to block the card and the reason behind it, such as suspected fraudulent activity or loss of the card. 4. The customer support representative will assist you further and initiate the blocking process. 5. If necessary, they will also guide you on the next steps, such as ordering a replacement card or disputing any unauthorized transactions. Remember, time is of the essence when it comes to card security, so please don't delay in reaching out to our customer support team. They are available Customer Support Working Hours to help you promptly and ensure the safety of your account. Rest assured, we're here to support you in any way we can. If you have any additional questions or concerns, feel free to let me know.",0.727273,1.0
63,i got to activate a master card on mobile how to do it,"[I'm here to assist you with activating your MasterCard on your mobile device. Here's how you can do it: 1. Make sure you have downloaded and installed the latest version of our mobile banking app on your device. 2. Open the app and log in to your account using your credentials. If you don't have an account yet, you may need to create one first. 3. Once you're logged in, navigate to the ""Cards"" or ""Account"" section of the app. 4. Look for the option to ""Activate a New Card"" or ""Activate Card."" 5. Select your MasterCard from the list of available cards and follow the on-screen prompts to complete the activation process. 6. You may be required to provide some card details, such as the card number, expiration date, and security code. Please have this information handy. 7. Once you've successfully activated your card, you should receive a confirmation message or notification within the app. If you encounter any issues during the activation process or need further assistance, please don't hesitate to reach out to our customer support team. They are available Customer Support Working Hours at Customer Support Phone Number or through the Live Chat option in the mobile app. Enjoy using your activated MasterCard on your mobile device! Let me know if there's anything else I can help you with.]","I'm here to assist you with activating your MasterCard on your mobile device. Here's how you can do it: 1. Make sure you have downloaded and installed the latest version of our mobile banking app on your device. 2. Open the app and log in to your account using your credentials. If you don't have an account yet, you may need to create one first. 3. Once you're logged in, navigate to the ""Cards"" or ""Account"" section of the app. 4. Look for the option to ""Activate a New Card"" or ""Activate Card."" 5. Select your MasterCard from the list of available cards and follow the on-screen prompts to complete the activation process. 6. You may be required to provide some card details, such as the card number, expiration date, and security code. Please have this information handy. 7. Once you've successfully activated your card, you should receive a confirmation message or notification within the app. If you encounter any issues during the activation process or need further assistance, please don't hesitate to reach out to our customer support team. They are available Customer Support Working Hours at Customer Support Phone Number or through the Live Chat option in the mobile app. Enjoy using your activated MasterCard on your mobile device! Let me know if there's anything else I can help you with.",0.785714,1.0
...,...,...,...,...,...
29,wanna cancel a loan where do i do i,"[I gather that you're looking to cancel your loan. I'm here to help you with that. To initiate the loan cancellation process, you'll need to reach out directly to our Loan Services Department. They have the expertise and resources to assist you with this request. You can contact them through our Customer Support Phone Number or send an email to Customer Support Email. They will guide you through the necessary steps and provide any additional information you may need. Remember, we're here to support you throughout the process. Let me know if there's anything else I can assist you with!]","I gather that you're looking to cancel your loan. I'm here to help you with that. To initiate the loan cancellation process, you'll need to reach out directly to our Loan Services Department. They have the expertise and resources to assist you with this request. You can contact them through our Customer Support Phone Number or send an email to Customer Support Email. They will guide you through the necessary steps and provide any additional information you may need. Remember, we're here to support you throughout the process. Let me know if there's anything else I can assist you with!",1.000000,1.0
28,id like to cancel a loan,"[I perceive that you would like to cancel your loan. I'm here to assist you with the process. However, as a customer service representative, I don't have access to specific loan details or the authority to cancel loans directly. It would be best to reach out to our loan department or speak with a loan officer who can guide you through the cancellation process. They will have the necessary information and tools to assist you promptly. You can reach our loan department at Loan Department Phone Number or visit our website to find the relevant contact information. Is there anything else I can assist you with regarding your loan?]","I perceive that you would like to cancel your loan. I'm here to assist you with the process. However, as a customer service representative, I don't have access to specific loan details or the authority to cancel loans directly. It would be best to reach out to our loan department or speak with a loan officer who can guide you through the cancellation process. They will have the necessary information and tools to assist you promptly. You can reach our loan department at Loan Department Phone Number or visit our website to find the relevant contact information. Is there anything else I can assist you with regarding your loan?",1.000000,1.0
26,"I want to check the mortgage payment, help me","[I'm here to assist you with checking your mortgage payment. Here's how you can do it: 1. Log in to your online banking or mortgage account. 2. Navigate to the section related to mortgage or loan payments. 3. Look for the option to view your payment history. 4. Select the specific payment you want to check. If you encounter any issues or have trouble finding the information, feel free to provide me with more details, such as the name of your bank or mortgage provider. I'm here to help you out!]","I'm here to assist you with checking your mortgage payment. Here's how you can do it: 1. Log in to your online banking or mortgage account. 2. Navigate to the section related to mortgage or loan payments. 3. Look for the option to view your payment history. 4. Select the specific payment you want to check. If you encounter any issues or have trouble finding the information, feel free to provide me with more details, such as the name of your bank or mortgage provider. I'm here to help you out!",1.000000,1.0
24,i cannot find my visa i need assistanec locking it,"[I'm sorry to hear that you're having trouble finding your Credit Card and need assistance locking it. I understand how important it is to protect your card from unauthorized use. Don't worry, I'm here to help you with that. To lock your Credit Card, please follow these steps: 1. Log in to your online banking account or open your banking app. 2. Navigate to the ""Cards"" or ""Manage Cards"" section. 3. Look for your Credit Card in the list of linked cards. 4. Select the option to ""Lock"" or ""Block"" your Credit Card. 5. Confirm the action by following any additional prompts or security measures. If you're unable to find the specific option or encounter any difficulties during the process, I recommend reaching out to your bank's customer support. They will be able to provide you with further assistance and guide you through the process. Remember, it's always crucial to keep your card details safe. If you suspect any fraudulent activity or have further concerns, please contact your bank immediately. If there's anything else I can assist you with, please feel free to let me know.]","I'm sorry to hear that you're having trouble finding your Credit Card and need assistance locking it. I understand how important it is to protect your card from unauthorized use. Don't worry, I'm here to help you with that. To lock your Credit Card, please follow these steps: 1. Log in to your online banking account or open your banking app. 2. Navigate to the ""Cards"" or ""Manage Cards"" section. 3. Look for your Credit Card in the list of linked cards. 4. Select the option to ""Lock"" or ""Block"" your Credit Card. 5. Confirm the action by following any additional prompts or security measures. If you're unable to find the specific option or encounter any difficulties during the process, I recommend reaching out to your bank's customer support. They will be able to provide you with further assistance and guide you through the process. Remember, it's always crucial to keep your card details safe. If you suspect any fraudulent activity or have further concerns, please contact your bank immediately. If there's anything else I can assist you with, please feel free to let me know.",1.000000,1.0
99,where can I check the card annuals fees?,"[I can assist you with that. To find the information about your card's annual fees, you have a few options: 1. Online Banking: If you have access to online banking, simply log in to your account on our website or mobile app. Navigate to the credit card section, where you should find a summary of your card details, including the annual fees. 2. Customer Service: Our knowledgeable customer service representatives are available to help you. You can reach them through our dedicated helpline at Customer Support Phone Number. They will be happy to provide you with the necessary information about the annual fees for your card. 3. Card Statement: The annual fees for your card are usually mentioned on your monthly card statement. Take a look at the ""Fees and Charges"" or ""Summary"" section, where you should find the details you're looking for. If you encounter any difficulties or need further assistance, please feel free to let me know. I'm here to help!]","I can assist you with that. To find the information about your card's annual fees, you have a few options: 1. Online Banking: If you have access to online banking, simply log in to your account on our website or mobile app. Navigate to the credit card section, where you should find a summary of your card details, including the annual fees. 2. Customer Service: Our knowledgeable customer service representatives are available to help you. You can reach them through our dedicated helpline at Customer Support Phone Number. They will be happy to provide you with the necessary information about the annual fees for your card. 3. Card Statement: The annual fees for your card are usually mentioned on your monthly card statement. Take a look at the ""Fees and Charges"" or ""Summary"" section, where you should find the details you're looking for. If you encounter any difficulties or need further assistance, please feel free to let me know. I'm here to help!",1.000000,1.0

In [16]:
raw_dataset.filter(lambda example: example['instruction'] == 'show me the loan payments')['response']

Column(['I\'ll do my best! I can help you with that. Checking your loan payments is a breeze. Here\'s what you need to do:\n\n1. Log in to your account on our website or app.\n2. Navigate to the "Loan" section or "My Loans" tab.\n3. Look for the "Payments" or "Payment History" option.\n4. Click on it to access your loan payment details.\n\nThere, you\'ll find a comprehensive record of your loan payments, including the due dates, amounts paid, and any outstanding balances. If you need further assistance or have any questions regarding your loan payments, feel free to reach out to our customer support team at {{Customer Support Phone Number}} or through the Live Chat on our website at {{Company Website URL}}. We\'re here to ensure a smooth loan payment experience for you.'])

In [17]:
raw_dataset

Dataset({
    features: ['tags', 'instruction', 'category', 'intent', 'response'],
    num_rows: 25545
})

### Answer correctness / answer similarty 
- Evaluate answers generated from LLM. Make sure it wont response not far away from ground truth

In [18]:

# 3. Initialize the stronger evaluator LLM
evaluator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4o-mini", temperature=0.0))

# 4. Load the specific retail banking dataset
print("Loading banking dataset from Hugging Face...")
raw_dataset = load_dataset("bitext/Bitext-retail-banking-llm-chatbot-training-dataset", split="train")

# 5. Select a small subset to evaluate (e.g., 50 rows) to manage costs and speed
EVAL_SAMPLE_SIZE = 100
eval_subset = raw_dataset.shuffle(seed=1).select(range(EVAL_SAMPLE_SIZE))

# 6. Lists to collect data for Ragas
questions = []
contexts = []      # Must be a list of lists of strings
answers = []       # NEW: Holds the final generated response from your LLM
ground_truths = []

# Define the regex pattern to match anything inside {{ }}
placeholder_pattern = r'\{\{.*?\}\}'


def unwrap_placeholders(text):
    """
    Dynamically removes the double curly braces {{ and }} but keeps the 
    inner text intact to maintain grammatical correctness.
    """
    if not isinstance(text, str):
        return text
    return re.sub(r'\{\{(.*?)\}\}', r'\1', text)


print(f"Starting end-to-end generation process for {EVAL_SAMPLE_SIZE} samples...")

# ==========================================
# Step 1: Run the Full Generation Pipeline
# ==========================================
for index, row in enumerate(eval_subset):
    query = row["instruction"]      # The user's question
    expected_truth = row["response"] # The gold standard answer
    
    print(f"[{index + 1}/{EVAL_SAMPLE_SIZE}] Generating response for: '{query[:50]}...'")
    
    # A. Retrieve context from Qdrant
    try:
        retrieved_data = get_banking_answer(query)
        retrieved_context = retrieved_data["answer"]
    except Exception as e:
        print(f"Error during retrieval: {e}")
        retrieved_context = "Error during retrieval"

    # B. Generate the final LLM response using your full RAG function
    try:
        generated_response = get_banking_answer_with_llm(query)
    except Exception as e:
        print(f"Error during generation: {e}")
        generated_response = "Error during generation"

    # C. Context Cleaning & Unwrapping (for Ragas inputs)
    if isinstance(retrieved_context, str):
        if retrieved_context.startswith("['") and retrieved_context.endswith("']"):
            try:
                parsed_list = ast.literal_eval(retrieved_context)
                if isinstance(parsed_list, list) and len(parsed_list) > 0:
                    retrieved_context = parsed_list[0]
            except Exception:
                retrieved_context = retrieved_context.strip("[]'\"").replace("\\'", "'")
        
        retrieved_context = retrieved_context.replace('\\n', '\n').replace('""', '"').strip()
        expected_truth = expected_truth.strip()
        
        # Unwrap placeholders for both retrieved contexts and references
        retrieved_context = unwrap_placeholders(retrieved_context)
        expected_truth = unwrap_placeholders(expected_truth)
        
        # Clean double spaces
        retrieved_context = re.sub(r'\s+', ' ', retrieved_context).strip()
        expected_truth = re.sub(r'\s+', ' ', expected_truth).strip()

    # Append to lists
    questions.append(query)
    contexts.append([retrieved_context])
    answers.append(generated_response)  # Collect your final LLM answer
    ground_truths.append(expected_truth)


# ==========================================
# Step 2: Batch Ragas Generation Evaluation
# ==========================================
print(f"\nInitiating end-to-end generation evaluation...")

# Construct the full evaluation dataset
# Ragas expects 'answer' to represent the generated response from your system
eval_data = {
    "question": questions,
    "contexts": contexts,
    "answer": answers,
    "ground_truth": ground_truths
}
ragas_dataset = Dataset.from_dict(eval_data)

# Configure the run to use 2 parallel workers
config = RunConfig(max_workers=2, timeout=60.0)

try:
    # Run evaluation comparing your LLM answers to the ground truths
    results = evaluate(
        dataset=ragas_dataset,
        metrics=[answer_correctness, answer_similarity],
        run_config=config,
        llm=evaluator_llm
    )
    
    # --- FINAL RESULTS DISPLAY ---
    
    print("\n=== OVERALL GENERATION AVERAGE SCORES ===")
    print(results)

    # Convert the results to a Pandas DataFrame
    df_results = results.to_pandas()
    
    print("\n=== DETAILED GENERATION BREAKDOWN ===")
    # Print matching columns for generation metrics in Ragas v0.2
    display(df_results[['user_input', 'response', 'reference', 'answer_correctness', 'answer_similarity']])

except Exception as e:
    print(f"\nGeneration evaluation failed: {e}")

C:\Users\vncpyy7h\AppData\Local\Temp\ipykernel_4196\1400776943.py:2: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  evaluator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4o-mini", temperature=0.0))

Loading banking dataset from Hugging Face...
Starting end-to-end generation process for 100 samples...
[1/100] Generating response for: 'i cant find my accfount fees i need help checking ...'
[2/100] Generating response for: 'I have made a mistake and I transferred money to t...'
[3/100] Generating response for: 'can I see the loan payment?...'
[4/100] Generating response for: 'i have to see the mortgage payments how could i do...'
[5/100] Generating response for: 'i cannot pay for my loan help me canceling it...'
[6/100] Generating response for: 'I need help to see the current balance on my cards...'
[7/100] Generating response for: 'I want to send money, ia it possible to perform a ...'
[8/100] Generating response for: 'wanna check the  fucking card annual fee i need as...'
[9/100] Generating response for: 'i dont have a fucking profile can ya help me creat...'
[10/100] Generating response for: 'I'm looking for a mortgaeg...'
[11/100] Generating response for: 'i got to check my fees can uhwlp me...'
[12/100] Generating response for: 'I can't find my fucking card annual fee, I need as...'
[13/100] Generating response for: 'I need to get back a swallowed card by an ATM , ca...'
[14/100] Generating response for: 'could ya help me to see the loan payments...'
[15/100] Generating response for: 'I would like to cancel a fucking bank transfer , w...'
[16/100] Generating response for: 'can  you help me to apply for a mortgage?...'
[17/100] Generating response for: 'I hve to send an email to fucking customer support...'
[18/100] Generating response for: 'can you tell me more about my fucking recent trans...'
[19/100] Generating response for: 'I am looking  for information about a branch in my...'
[20/100] Generating response for: 'I got to see the loan  payments, I need help...'
[21/100] Generating response for: 'wanna cancel a bank transfer can ya help me...'
[22/100] Generating response for: 'i need information about the fucking credit card a...'
[23/100] Generating response for: 'i have to chewck the loan payment help me...'
[24/100] Generating response for: 'im travelling overseas how do i activate a master ...'
[25/100] Generating response for: 'i cannot find my visa i need assistanec locking it...'
[26/100] Generating response for: 'I would like to find the closest branhc, help me...'
[27/100] Generating response for: 'I want to check the mortgage payment, help me...'
[28/100] Generating response for: 'I'm traveling overseas I'd like to activate a visa...'
[29/100] Generating response for: 'id like to cancel a loan...'
[30/100] Generating response for: 'wanna cancel a loan where do i do i...'
[31/100] Generating response for: 'i do not wanna pay for my loan help me to cancel i...'
[32/100] Generating response for: 'I don't have a fucking account, could you help me ...'
[33/100] Generating response for: 'I got to activate a Master Card...'
[34/100] Generating response for: 'I made a mistake and I have transferred money to t...'
[35/100] Generating response for: 'wanns send money to someone i need assistance to m...'
[36/100] Generating response for: 'need to block an amex online how can i do it...'
[37/100] Generating response for: 'wanna find the nearest atm i need hlp...'
[38/100] Generating response for: 'I'd like to block an credit card on mobile, can yo...'
[39/100] Generating response for: 'I'd like to know about my fees...'
[40/100] Generating response for: 'wanna check the <fucking> current balance of my ba...'
[41/100] Generating response for: 'acn I search for an ATM near?...'
[42/100] Generating response for: 'I'd like to check the fucking card annual fees, wh...'
[43/100] Generating response for: 'i dont understnd ui need assistance talking to a p...'
[44/100] Generating response for: 'i have to cancel an fucking bank transfer to a con...'
[45/100] Generating response for: 'i got to check the loan payment how do i do it...'
[46/100] Generating response for: 'I want to send money to someone, how do I perform ...'
[47/100] Generating response for: 'can ya help me see the fucking bank statement...'
[48/100] Generating response for: 'i cant pay for my mortgage can uhelp me cancel it...'
[49/100] Generating response for: 'need to send an email to customer service will ya ...'
[50/100] Generating response for: 'I don't want to pay for my loan, could youhelp me ...'
[51/100] Generating response for: 'i want assistanec to cancel a loan...'
[52/100] Generating response for: 'I want to apply for a loan, I need help...'
[53/100] Generating response for: 'I would like to cancel a Master Card on mobile, co...'
[54/100] Generating response for: 'I got to dispute an ATM withdrawal, could I get so...'
[55/100] Generating response for: 'I got to close a fucking user account, how do I do...'
[56/100] Generating response for: 'wanna send money to someone online how could i mak...'
[57/100] Generating response for: 'I'd like to activate an amex for international usa...'
[58/100] Generating response for: 'id like ot apply for a mortgage i need assistance...'
[59/100] Generating response for: 'id liek to close a fucking online account will uhe...'
[60/100] Generating response for: 'I have to disputea withdrawal...'
[61/100] Generating response for: 'I made a mistake, help me canceling a bank transfe...'
[62/100] Generating response for: 'wanna check the <fucking> current balance of my ba...'
[63/100] Generating response for: 'I got to check the current balance on my card, whe...'
[64/100] Generating response for: 'i got to activate a master card on mobile how to d...'
[65/100] Generating response for: 'i got to see the mortagge payments how to do it...'
[66/100] Generating response for: 'I can't pay for my mortgage, help me t cancel it...'
[67/100] Generating response for: 'I can't pay for my loan, can I cancel it ?...'
[68/100] Generating response for: 'i want assistance activating a credit cardd online...'
[69/100] Generating response for: 'wanna send money to someone I'd like to make a tra...'
[70/100] Generating response for: 'I would like to see the mortgage payment, could I ...'
[71/100] Generating response for: 'i want help  canceling a loan...'
[72/100] Generating response for: 'I'd like to speak with a fucking operator, how can...'
[73/100] Generating response for: 'I want ti open a fucking user account...'
[74/100] Generating response for: 'would ti be possible to cancel a visa on mobile...'
[75/100] Generating response for: 'I want to know about the fucking current balance o...'
[76/100] Generating response for: 'I got to retrieve a credit card  by an ATM, how do...'
[77/100] Generating response for: 'I want to talk to customer support, where could I ...'
[78/100] Generating response for: 'i got to see the fuccking recent transaction detai...'
[79/100] Generating response for: 'I want to see the loan payments, how to do it ?...'
[80/100] Generating response for: 'the ATM did not return my credit card, how can I g...'
[81/100] Generating response for: 'i got to activate a amex for international usage c...'
[82/100] Generating response for: 'I don't want to pay for my loan, could you cancel ...'
[83/100] Generating response for: 'I am trying to find a loan, can you help me?...'
[84/100] Generating response for: 'how could i activate an card on mobile...'
[85/100] Generating response for: 'id like to see the current balance of my bank acco...'
[86/100] Generating response for: 'there is a withdrawalo i didnt make what can i do...'
[87/100] Generating response for: 'need to check the fucking recent transaction detai...'
[88/100] Generating response for: 'my card has been stolen, I want to block it?...'
[89/100] Generating response for: 'I need to regster an online account...'
[90/100] Generating response for: 'i cant find my account fees can uhelp me checking ...'
[91/100] Generating response for: 'where could I cancel a loan?...'
[92/100] Generating response for: 'I have to locfk a card, will you help me?...'
[93/100] Generating response for: 'I need to check the mortgage payment, will you hel...'
[94/100] Generating response for: 'i need cash how to search for a branch...'
[95/100] Generating response for: 'I am looking for information about the nearest bra...'
[96/100] Generating response for: 'I would like to cancel a fucking profile , how do ...'
[97/100] Generating response for: 'i cannot pay for my loan i need assistance to canc...'
[98/100] Generating response for: 'wanna activate a visa on mobile how can i do it...'
[99/100] Generating response for: 'need to set up an password where can i do it...'
[100/100] Generating response for: 'where can I check the card annuals fees?...'

Initiating end-to-end generation evaluation...

Evaluating:   0%|          | 0/200 [00:00<?, ?it/s]

=== OVERALL GENERATION AVERAGE SCORES ===
{'answer_correctness': 0.9423, 'answer_similarity': 0.9764}

=== DETAILED GENERATION BREAKDOWN ===

,user_input,response,reference,answer_correctness,answer_similarity
0,i cant find my accfount fees i need help checking them,"I'm genuinely sorry for the inconvenience you're experiencing in locating your account fees. I'm here to help you with that. To check your account fees, please follow these steps:\n\n1. Log in to your account on our website.\n2. Navigate to the ""Account"" or ""Profile"" section.\n3. Look for an option like ""View Account Fees"" or ""Billing Information"".\n4. Click on that option to access detailed information about your account fees.\n\nIf you're unable to locate the account fees or need further assistance, please provide me with your account details or any other relevant information, and I'll gladly assist you further.","I'm genuinely sorry for the inconvenience you're experiencing in locating your account fees. I'm here to help you with that. To check your account fees, please follow these steps: 1. Log in to your account on our website. 2. Navigate to the ""Account"" or ""Profile"" section. 3. Look for an option like ""View Account Fees"" or ""Billing Information"". 4. Click on that option to access detailed information about your account fees. If you're unable to locate the account fees or need further assistance, please provide me with your account details or any other relevant information, and I'll gladly assist you further.",0.999025,0.996101
1,"I have made a mistake and I transferred money to the wrong account, could you help me cancelling a transfer?","1. Please accept my apologies for any inconvenience caused by the mistaken bank transfer. I understand how important it is to resolve this issue for you. Rest assured, I'm here to help you cancel the transfer to the wrong account.\n\n2. To proceed with canceling the transfer, we'll need some specific details. Please provide me with the following information:\n - Your {{Name}}: So I can verify your account details.\n - Date and time of the transfer: This will assist in locating the transaction.\n - The amount and currency transferred: This helps identify the specific transaction among others.\n\n3. Once I have these details, I'll escalate the issue to our support team, who will take the necessary steps to cancel the transfer. Please note that depending on the circumstances, cancellation may not always be guaranteed. However, we'll do everything we can to assist you.\n\n4. If you have any additional questions or concerns, feel free to let me know. We're here to provide you with the support you need.","Please accept my apologies for any inconvenience caused by the mistaken bank transfer. I understand how important it is to resolve this issue for you. Rest assured, I'm here to help you cancel the transfer to the wrong account. To proceed with canceling the transfer, we'll need some specific details. Please provide me with the following information: 1. Your Name: So I can verify your account details. 2. Date and time of the transfer: This will assist in locating the transaction. 3. The amount and currency transferred: This helps identify the specific transaction among others. Once I have these details, I'll escalate the issue to our support team, who will take the necessary steps to cancel the transfer. Please note that depending on the circumstances, cancellation may not always be guaranteed. However, we'll do everything we can to assist you. If you have any additional questions or concerns, feel free to let me know. We're here to provide you with the support you need.",0.957324,0.972153
2,can I see the loan payment?,"1. Log in to your account on our website or mobile app.\n2. Navigate to the ""Loan"" or ""Account"" section.\n3. You should be able to find the information you need regarding your loan payment details.\n\nIf you encounter any issues or have trouble locating the payment details, please let me know, and I'll guide you through the process.","I'd be happy to assist you in checking your loan payment. To view your loan payment details, you can log in to your account on our website or mobile app. Once you're logged in, navigate to the ""Loan"" or ""Account"" section, where you should be able to find the information you need. If you encounter any issues or have trouble locating the payment details, please let me know, and I'll guide you through the process.",0.992272,0.969087
3,i have to see the mortgage payments how could i do it,"Here are the steps to check your mortgage payments:\n\n1. Login to your {{Online Banking}} account.\n2. Navigate to the {{Mortgage Payments}} section.\n3. Look for an option like ""View Mortgage Payments"" or ""Payment History"".\n4. Click on it to access the details of your mortgage payments.\n\nIf you need further assistance or encounter any difficulties, feel free to let me know. I'm here to assist you every step of the way!","I'm here to help you check your mortgage payments. Here's what you can do: 1. Login to your Online Banking account. 2. Navigate to the Mortgage Payments section. 3. Look for an option like ""View Mortgage Payments"" or ""Payment History"". 4. Click on it to access the details of your mortgage payments. If you need further assistance or encounter any difficulties, feel free to let me know. I'm here to assist you every step of the way!",0.994726,0.978904
4,i cannot pay for my loan help me canceling it,"I'm sorry to hear that you're facing difficulty in paying for your loan. I'm here to help you with canceling it. \n\nTo initiate the cancellation process, please follow these steps:\n\n1. Contact our customer support team at {{Customer Support Phone Number}} or email us at {{Customer Support Email Address}} and explain your situation. They will guide you through the cancellation process and provide you with the necessary instructions.\n\n2. Make sure to provide them with your loan details and any relevant information, such as your loan account number or loan agreement number. This will assist them in locating your loan and processing the cancellation request more efficiently.\n\n3. If needed, our customer support team might require additional documentation or information from you to complete the cancellation process. Please be prepared to provide any requested documents promptly.\n\n4. Once your cancellation request has been processed, you will receive confirmation along with any further instructions or actions you need to take.\n\nIf you have any further questions or concerns, please don't hesitate to reach out to our customer support team. They are available to assist you and provide further guidance throughout the cancellation process.","I'm sorry to hear that you're facing difficulty in paying for your loan. I'm here to help you with canceling it. To initiate the cancellation process, please follow these steps: 1. Contact our customer support team at Customer Support Phone Number or email us at Customer Support Email Address and explain your situation. They will guide you through the cancellation process and provide you with the necessary instructions. 2. Make sure to provide them with your loan details and any relevant information, such as your loan account number or loan agreement number. This will assist them in locating your loan and processing the cancellation request more efficiently. 3. If needed, our customer support team might require additional documentation or information from you to complete the cancellation process. Please be prepared to provide any requested documents promptly. 4. Once your cancellation request has been processed, you will receive confirmation along with any further instructions or actions you need to take. If you have any further questions or concerns, please don't hesitate to reach out to our customer support team. They are available to assist you and provide further guidance throughout the cancellation process.",0.971852,0.984182
...,...,...,...,...,...
95,"I would like to cancel a fucking profile , how do I do it?","I understand the inconvenience, and I'm sorry for any frustration or inconvenience you may have encountered with your user account. I understand that you would like to cancel your profile. I'm here to assist you with that. \n\nTo cancel your profile, please follow these steps:\n\n1. Log in to your account on our website.\n2. Navigate to your account settings or profile settings.\n3. Look for the option to cancel or delete your profile.\n4. Follow the provided instructions to confirm the cancellation.\n\nIf you encounter any difficulties or need further assistance during the process, please don't hesitate to reach out to our customer support team. We're available {{Customer Support Working Hours}} at {{Customer Support Phone Number}} or you can chat with us through the Live Chat function on our website at {{Company Website URL}}.\n\nWe appreciate your understanding and we're here to help ensure a smooth cancellation process for you.","I understand the inconvenience, and I'm sorry for any frustration or inconvenience you may have encountered with your user account. I understand that you would like to cancel your profile. I'm here to assist you with that. To cancel your profile, please follow these steps: 1. Log in to your account on our website. 2. Navigate to your account settings or profile settings. 3. Look for the option to cancel or delete your profile. 4. Follow the provided instructions to confirm the cancellation. If you encounter any difficulties or need further assistance during the process, please don't hesitate to reach out to our customer support team. We're available Customer Support Working Hours at Customer Support Phone Number or you can chat with us through the Live Chat function on our website at Company Website URL. We appreciate your understanding and we're here to help ensure a smooth cancellation process for you.",0.995449,0.981794
96,i cannot pay for my loan i need assistance to cancel it,"1. I'm sorry to hear that you're experiencing difficulties making payments for your loan. I understand that canceling the loan may be a viable option for you. Let's work together to find a solution.\n\n2. Before we proceed with canceling your loan, I suggest reaching out to our dedicated {{Loan Support Team}}. They are equipped to offer personalized assistance that aligns with your specific situation. They can explore potential alternatives, such as adjusting the payment plan or offering temporary relief options.\n\n3. To contact our {{Loan Support Team}}, you can reach them at {{Loan Support Phone Number}} or via email at {{Loan Support Email Address}}. They'll be more than happy to provide guidance and support in canceling your loan if necessary.\n\n4. Remember, we're here to help and find the best outcome for you. Let me know if there's anything else I can assist you with.","I'm sorry to hear that you're experiencing difficulties making payments for your loan. I understand that canceling the loan may be a viable option for you. Let's work together to find a solution. Before we proceed with canceling your loan, I suggest reaching out to our dedicated Loan Support Team. They are equipped to offer personalized assistance that aligns with your specific situation. They can explore potential alternatives, such as adjusting the payment plan or offering temporary relief options. To contact our Loan Support Team, you can reach them at Loan Support Phone Number or via email at Loan Support Email Address. They'll be more than happy to provide guidance and support in canceling your loan if necessary. Remember, we're here to help and find the best outcome for you. Let me know if there's anything else I can assist you with.",0.955899,0.981489
97,wanna activate a visa on mobile how can i do it,"1. Download the mobile banking app of your card issuer from your device's app store.\n2. Open the app and log in to your account using your credentials.\n3. Look for the ""Manage Cards"" or ""My Cards"" section within the app.\n4. Find your Visa from the list of cards associated with your account.\n5. Select the option to activate the card.\n6. Follow the on-screen instructions to complete the activation process. This may involve entering the card details or verifying your identity.\n7. Once the activation is successful, you will receive a confirmation message.\n\nIf you encounter any difficulties during the activation process or have any further questions, please don't hesitate to reach out. I'm here to assist you every step of the way!","I can help you activate your Credit Card on your mobile device. Activating a Credit Card on mobile is a quick and easy process. Here's what you need to do: 1. Download the mobile banking app of your card issuer from your device's app store. 2. Open the app and log in to your account using your credentials. 3. Look for the ""Manage Cards"" or ""My Cards"" section within the app. 4. Find your Credit Card from the list of cards associated with your account. 5. Select the option to activate the card. 6. Follow the on-screen instructions to complete the activation process. This may involve entering the card details or verifying your identity. 7. Once the activation is successful, you will receive a confirmation message. If you encounter any difficulties during the activation process or have any further questions, please don't hesitate to reach out. I'm here to assist you every step of the way!",0.889395,0.948884
98,need to set up an password where can i do it,"I'm happy to help! Here’s what you need to do to set up a password for your account:\n\n1. Go to the ""{{Account Settings}}"" or ""{{Profile}}"" section on our website.\n2. Look for the ""Password"" or ""Security"" tab.\n3. Click on the tab and you'll be directed to the password setup page.\n4. Follow the instructions to create a strong and secure password. Make sure it meets the required criteria (e.g., a mix of uppercase and lowercase letters, numbers, and special characters).\n5. Once you've entered and confirmed your new password, click on the ""Save"" or ""Update"" button.\n\nIf you encounter any difficulties or have any questions during the process, please don't hesitate to let me know. I'm here to make it as smooth as possible for you!","I'm happy to help! I can assist you in setting up a password for your account. Here's what you need to do: 1. Go to the ""Account Settings"" or ""Profile"" section on our website. 2. Look for the ""Password"" or ""Security"" tab. 3. Click on the tab and you'll be directed to the password setup page. 4. Follow the instructions to create a strong and secure password. Make sure it meets the required criteria (e.g., a mix of uppercase and lowercase letters, numbers, and special characters). 5. Once you've entered and confirmed your new password, click on the ""Save"" or ""Update"" button. If you encounter any difficulties or have any questions during the process, please don't hesitate to let me know. I'm here to make it as smooth as possible for you!",0.899693,0.973771
99,where can I check the card annuals fees?,"I can assist you with that. To find the information about your card's annual fees, you have a few options:\n\n1. Online Banking: If you have access to online banking, simply log in to your account on our website or mobile app. Navigate to the credit card section, where you should find a summary of your card details, including the annual fees.\n\n2. Customer Service: Our knowledgeable customer service representatives are available to help you. You can reach them through our dedicated helpline at {{Customer Support Phone Number}}. They will be happy to provide you with the necessary information about the annual fees for your card.\n\n3. Card Statement: The annual fees for your card are usually mentioned on your monthly card statement. Take a look at the ""Fees and Charges"" or ""Summary"" section, where you should find the details you're looking for.\n\nIf you encounter any difficulties or need further assistance, please feel free to let me know. I'm here to help!","I can assist you with that. To find the information about your card's annual fees, you have a few options: 1. Online Banking: If you have access to online banking, simply log in to your account on our website or mobile app. Navigate to the credit card section, where you should find a summary of your card details, including the annual fees. 2. Customer Service: Our knowledgeable customer service representatives are available to help you. You can reach them through our dedicated helpline at Customer Support Phone Number. They will be happy to provide you with the necessary information about the annual fees for your card. 3. Card Statement: The annual fees for your card are usually mentioned on your monthly card statement. Take a look at the ""Fees and Charges"" or ""Summary"" section, where you should find the details you're looking for. If you encounter any difficulties or need further assistance, please feel free to let me know. I'm here to help!",0.998135,0.992541

In [19]:
df_results[['user_input', 'response', 'reference', 'answer_correctness', 'answer_similarity']].sort_values(by='answer_correctness').head(20)

,user_input,response,reference,answer_correctness,answer_similarity
91,"I have to locfk a card, will you help me?","1. Contact our {{Customer Support Team}} immediately, either through our website or by calling {{Customer Support Phone Number}}.\n2. Provide the agent with your card details, such as the card number or account information, to verify your identity.\n3. Explain that you want to block the card and the reason behind it, such as suspected fraudulent activity or loss of the card.\n4. The customer support representative will assist you further and initiate the blocking process.\n5. If necessary, they will also guide you on the next steps, such as ordering a replacement card or disputing any unauthorized transactions.\n\nRemember, time is of the essence when it comes to card security, so please don't delay in reaching out to our customer support team. They are available {{Customer Support Working Hours}} to help you promptly and ensure the safety of your account.","I'm here to assist you with blocking your card. I understand the importance of this matter and I'll guide you through the process. To block your card, please follow these steps: 1. Contact our Customer Support Team immediately, either through our website or by calling Customer Support Phone Number. 2. Provide the agent with your card details, such as the card number or account information, to verify your identity. 3. Explain that you want to block the card and the reason behind it, such as suspected fraudulent activity or loss of the card. 4. The customer support representative will assist you further and initiate the blocking process. 5. If necessary, they will also guide you on the next steps, such as ordering a replacement card or disputing any unauthorized transactions. Remember, time is of the essence when it comes to card security, so please don't delay in reaching out to our customer support team. They are available Customer Support Working Hours to help you promptly and ensure the safety of your account. Rest assured, we're here to support you in any way we can. If you have any additional questions or concerns, feel free to let me know.",0.763757,0.968072
94,"I am looking for information about the nearest branch, where can I get it?","1. Visit our website at {{Company Website URL}}. On the homepage, look for a section called ""Find a Branch"" or ""Branch Locator."" Click on it, and you'll be able to search for the nearest branch by entering your location or ZIP code. The website will provide you with the branch's address, contact information, and even directions if needed.\n\n2. If you prefer speaking to a live representative, you can reach out to our friendly customer support team at {{Customer Support Phone Number}}. They will gladly assist you in finding the nearest branch and provide all the necessary information you're looking for.","Finding information about the nearest branch is crucial, and I'm here to guide you. To get the details you need, you have a couple of options: 1. Visit our website at Company Website URL. On the homepage, look for a section called ""Find a Branch"" or ""Branch Locator."" Click on it, and you'll be able to search for the nearest branch by entering your location or ZIP code. The website will provide you with the branch's address, contact information, and even directions if needed. 2. If you prefer speaking to a live representative, you can reach out to our friendly customer support team at Customer Support Phone Number. They will gladly assist you in finding the nearest branch and provide all the necessary information you're looking for. Remember, we have a dedicated team ready to help you at any time, so don't hesitate to reach out if you have any further questions or need assistance.",0.773390,0.975911
44,i got to check the loan payment how do i do it,"1. Log in to your account on our website.\n2. Navigate to the ""Loan"" or ""My Account"" section.\n3. Look for the option to view your loan details or payments.\n4. Click on it to access your loan payment information.","I'm here to assist you with checking your loan payment. Here's how you can do it: 1. Log in to your account on our website. 2. Navigate to the ""Loan"" or ""My Account"" section. 3. Look for the option to view your loan details or payments. 4. Click on it to access your loan payment information. If you're having trouble finding it or need more specific guidance, please let me know. I'll be more than happy to help you navigate through the process.",0.786431,0.963904
52,"I would like to cancel a Master Card on mobile, could I get some help?","1. Open the mobile banking app on your device.\n2. Navigate to the ""Cards"" or ""Account"" section.\n3. Locate your Master Card in the list of cards.\n4. Look for the option to ""Manage"" or ""Cancel"" your card.\n5. Follow the on-screen prompts to initiate the cancellation process.\n6. If you encounter any issues or need further guidance, don't hesitate to reach out to our customer support team at {{Customer Support Phone Number}} or through the Live Chat on our website at {{Company Website URL}}.\n\nPlease keep in mind that canceling your Master Card will result in the termination of all associated services and benefits. If you have any outstanding balance or pending transactions, make sure to settle them before canceling to avoid any potential issues. If you require any additional assistance or have any further questions, feel free to let me know.","I understand that you would like to cancel your Master Card on your mobile device. I'm here to assist you with that. Here's what you need to do: 1. Open the mobile banking app on your device. 2. Navigate to the ""Cards"" or ""Account"" section. 3. Locate your Master Card in the list of cards. 4. Look for the option to ""Manage"" or ""Cancel"" your card. 5. Follow the on-screen prompts to initiate the cancellation process. 6. If you encounter any issues or need further guidance, don't hesitate to reach out to our customer support team at Customer Support Phone Number or through the Live Chat on our website at Company Website URL. Please keep in mind that canceling your Master Card will result in the termination of all associated services and benefits. If you have any outstanding balance or pending transactions, make sure to settle them before canceling to avoid any potential issues. If you require any additional assistance or have any further questions, feel free to let me know.",0.789934,0.977898
59,I have to disputea withdrawal,"Certainly! Here are the steps to dispute a withdrawal:\n\n1. Contact our {{Customer Support Team}} as soon as possible.\n2. Provide them with the details of the disputed transaction, including the date, time, and amount.\n3. They will guide you through the dispute process and assist you in filing a complaint with the appropriate department.\n\nRest assured, we take these matters seriously, and we will investigate the transaction thoroughly to ensure a satisfactory resolution. If you have any further questions or need additional assistance, please don't hesitate to let me know.","Certainly, I can assist you with that! I understand that you want to dispute a withdrawal. Unauthorized transactions can be frustrating, but we'll work together to resolve the issue. Here's what you need to do: 1. Contact our Customer Support Team as soon as possible. 2. Provide them with the details of the disputed transaction, including the date, time, and amount. 3. They will guide you through the dispute process and assist you in filing a complaint with the appropriate department. Rest assured, we take these matters seriously, and we will investigate the transaction thoroughly to ensure a satisfactory resolution. If you have any further questions or need additional assistance, please don't hesitate to let me know.",0.800419,0.951674
67,i want assistance activating a credit cardd online,"1. Visit our website at {{Company Website URL}} and log in to your account using your credentials.\n2. Navigate to the ""Account"" or ""Profile"" section.\n3. Look for the option to ""Activate Card"" or ""Manage Cards"" and click on it.\n4. Follow the on-screen instructions to enter the required details such as your credit card number, expiration date, and any other information requested.\n5. Once you've entered the necessary information, click on the ""Activate"" or ""Submit"" button.\n6. You may be prompted to set a PIN for your card during the activation process. If so, choose a PIN that is easy for you to remember but difficult for others to guess.\n\nIf you encounter any issues or have any questions during the activation process, please feel free to reach out to our customer support team at {{Customer Support Phone Number}} or through the Live Chat on our website. We're here to provide you with the assistance you need.","I'm here to assist you with activating your credit card online. Activating your credit card is a simple process that can be done conveniently from your computer or mobile device. Here's what you need to do: 1. Visit our website at Company Website URL and log in to your account using your credentials. 2. Navigate to the ""Account"" or ""Profile"" section. 3. Look for the option to ""Activate Card"" or ""Manage Cards"" and click on it. 4. Follow the on-screen instructions to enter the required details such as your credit card number, expiration date, and any other information requested. 5. Once you've entered the necessary information, click on the ""Activate"" or ""Submit"" button. 6. You may be prompted to set a PIN for your card during the activation process. If so, choose a PIN that is easy for you to remember but difficult for others to guess. If you encounter any issues or have any questions during the activation process, please feel free to reach out to our customer support team at Customer Support Phone Number or through the Live Chat on our website. We're here to provide you with the assistance you need.",0.801624,0.956497
66,"I can't pay for my loan, can I cancel it ?","I'm sorry to hear that you're having difficulty with your loan payments. Here are the steps you can take:\n\n1. Understand that canceling a loan may not be an available option.\n2. Reach out to our dedicated customer support team at {{Customer Support Phone Number}}.\n3. Alternatively, you can contact us via our live chat on our website at {{Company Website URL}}.\n4. Our team will review your specific situation and provide guidance on the best course of action.\n\nRest assured, we're here to support you.","I'm sorry to hear that you're having difficulty with your loan payments. Understanding the challenges that financial obligations can bring, we strive to provide assistance whenever possible. While canceling a loan may not be an available option, we have alternative solutions to help you navigate this situation. I recommend reaching out to our dedicated customer support team at Customer Support Phone Number or via our live chat on our website at Company Website URL. They will be able to review your specific situation and provide guidance on the best course of action. Rest assured, we're here to support you.",0.804801,0.969202
78,"I want to see the loan payments, how to do it ?","Here’s how you can check your loan payments:\n\n1. Login to your online account using your credentials.\n2. Navigate to the ""Loan Payments"" section or a similar option available on the dashboard.\n3. Once you're on the loan payments page, you should be able to view a list of your recent payments including the payment dates and amounts. Some systems might provide it as a statement or transaction history.\n4. If you need more details about a specific payment, click on the payment or transaction to expand it and gain further information.\n\nIf you encounter any issues during this process or if you need further assistance, feel free to let me know. I'm here to help!","I'd be glad to assist you with checking your loan payments. Here's what you need to do: 1. Login to your online account using your credentials. 2. Navigate to the ""Loan Payments"" section or a similar option available on the dashboard. 3. Once you're on the loan payments page, you should be able to view a list of your recent payments including the payment dates and amounts. Some systems might provide it as a statement or transaction history. 4. If you need more details about a specific payment, click on the payment or transaction to expand it and gain further information. If you encounter any issues during this process or if you need further assistance, feel free to let me know. I'm here to help!",0.808359,0.983437
50,i want assistanec to cancel a loan,"1. Contact our {{Loan Department}} either through phone or email, or visit our {{Website}}.\n2. Provide them with your {{Loan Information}} such as your loan account number or any other required details.\n3. Explain your situation and why you would like to cancel the loan. They will guide you further and advise on the necessary steps.\n4. Follow any instructions or documentation requests provided by our loan department to proceed with the cancellation.\n5. If there are any outstanding balances or fees associated with the loan, our representative will provide you with the necessary information to settle them.\n\nPlease keep in mind that the specific cancellation process may vary depending on the type of loan and the terms and conditions associated with it. Our loan department will be able to guide you through the process and address any concerns or questions you may have.","I can assist you with canceling your loan. Canceling a loan typically involves a few steps to ensure a smooth process. Here's what you need to do: 1. Contact our Loan Department either through phone or email, or visit our Website. 2. Provide them with your Loan Information such as your loan account number or any other required details. 3. Explain your situation and why you would like to cancel the loan. They will guide you further and advise on the necessary steps. 4. Follow any instructions or documentation requests provided by our loan department to proceed with the cancellation. 5. If there are any outstanding balances or fees associated with the loan, our representative will provide you with the necessary information to settle them. Please keep in mind that the specific cancellation process may vary depending on the type of loan and the terms and conditions associated with it. Our loan department will be able to guide you through the process and address any concerns or questions you may have. If you have any further queries or need additional assistance, feel free to let me know. I'm here to help!",0.813519,0.968363
21,i need information about the fucking credit card annual fees where could i find it,"1. Visit our website at {{Company Website URL}}.\n2. Navigate to the ""Credit Cards"" section.\n3. Select the specific credit card you want to know about.\n4. Look for the ""Rates and Fees"" or ""Pricing and Terms"" section.\n5. The credit card annual fee information should be listed there.\n\nIf you have any further questions or if there's anything else I can assist you with, please feel free to let me know.","We acknowledge the issue, and we're sorry for any inconvenience you've faced regarding the credit card annual fees. I completely understand your need for information on this matter. Allow me to assist you. To find details about credit card annual fees, you can follow these steps: 1. Visit our website at Company Website URL. 2. Navigate to the ""Credit Cards"" section. 3. Select the specific credit card you want to know about. 4. Look for the ""Rates and Fees"" or ""Pricing and Terms"" section. 5. The credit card annual fee information should be listed there. If you have any further questions or if there's anything else I can assist you with, please feel free to let me know.",0.819869,0.946144
70,i want help canceling a loan,"To cancel your loan, please follow these steps:\n\n1. Contact our customer support team at {{Customer Support Phone Number}} or through our Live Chat service on our website at {{Company Website URL}}. They will be able to provide you with the necessary guidance and assist you with canceling your loan.\n\n2. Prepare any relevant information or documentation related to your loan, such as your loan account number or any supporting documents you may have.\n\n3. When contacting our customer support team, clearly explain your intention to cancel the loan. They may ask you for specific details to verify your identity and locate your loan account.\n\n4. Once the cancellation process is initiated, our customer support team will guide you through the next steps, which may include filling out a cancellation form or providing additional information.\n\n5. Take note of any confirmation numbers or reference numbers provided by our customer support team. This will serve as proof of your loan cancellation.\n\nIf you have any further questions or require additional assistance, please don't hesitate to reach out. We're here to help you throughout the cancellation process.","I'm sorry to hear that you're looking to cancel a loan. I'll do my best to assist you with that. To cancel your loan, please follow these steps: 1. Contact our customer support team at Customer Support Phone Number or email us at Customer Support Email Address. They will guide you through the cancellation process and provide any necessary forms or documentation. 2. Make sure to have your loan details ready, such as the loan account number, loan amount, and any applicable identification information. 3. Depending on the type of loan, there may be specific terms and conditions for cancellation. Our customer support team will be able to provide you with all the necessary information. 4. It's important to note that there may be fees or penalties associated with loan cancellations. Our customer support team will inform you of any applicable charges. If you have any further questions or need assistance, feel free to reach out to our customer support team. We're here to help make this process as smooth as possible for you.",0.830129,0.957008